### ISSUE TITLE
Increase Dynmaic Header to avoid Fingerprinting Protection

### ISSUE THREAD

**Issue by ZKSYNCDEV** [MatrixTM/MHDDoS#408]
### Which section is this feature request for?

L7 (DDoS Attack Layer 7)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Modern fingerprinting methods will detect and reduce the performance of the script, We should be able to send traffic that matches real Browser traffic in every low-level aspect such as TLS-Handshake, HTTP2 Settings, HTTP Headers and etc.

### Describe the solution you'd like

Modern fingerprinting methods will detect and reduce the performance of the script, We should be able to send traffic that matches real Browser traffic in every low-level aspect such as TLS-Handshake, HTTP2 Settings, HTTP Headers and etc.

**Comment by Nexuzzzz** [comment]
the best way to do this is to create a json file for every browser "profile", with hardcoded headers, tls ciphers and protocols etc etc.
Since i will be implementing the said idea, here are some good links to get started with everything

- https://hussainaliakbar.github.io/restricting-tls-version-and-cipher-suites-in-python-requests-and-testing-with-wireshark/
- https://fingerprint.com/blog/what-is-tls-fingerprinting-transport-layer-security/
