### ISSUE TITLE
[BUG Report]:No module named 'PyRoxy'

### ISSUE THREAD

**Issue by Hackerreplit** [MatrixTM/MHDDoS#418]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: [e.g. Ubuntu]
- Installed Requirements Version [e.g. PyRoxy1.0b5]
- Python Version [e.g. 3.8.x]
```

### What happened (Describe the bug) ?

Bug in the PyRoxy

### Screenshots

https://h.top4top.io/p_2484k1c9t0.jpg

### Relevant log output

```shell
<module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'
```

**Comment by Hackerreplit** [comment]
OK IS GOOD I USE GOOGLE SHELL BUT ON SAFE MODE

**Comment by DIMNISSV** [comment]
When I encountered this problem, using the command helped me **`python start.py ...`** instead of `py start.py ...`, although both in `py` and in `python` in the interpreter `sys.executable` pointed to the correct path. I'm not sure what this is related to. _Note, I have been working with a virtual environment._

**Comment by FledPaul** [comment]
Make sure to install **all** required libraries.
`pip install -r requirements.txt`

**Comment by Khnaz35** [comment]
[07:46:42 - INFO] Downloading Proxies from 50 Providers
[07:46:51 - INFO] 73,404 Proxies are getting checked, this may take awhile!

I am kinda stuck at this point its been taking hours but no output or response from system afterward not sure where is the issue
